spring:
  application:
    name: guildaaventureiro

  cache:
    type: simple

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: apppass

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  elasticsearch:
    uris: http://localhost:9200

  data:
    elasticsearch:
      repositories:
        enabled: true
